# Generated by Django 6.1 on 2026-08-31 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_skills', models.TextField()),
                ('career_interest', models.CharField(max_length=100)),
                ('enjoyed_field', models.CharField(max_length=100)),
                ('skill_score', models.IntegerField(default=0)),
                ('recommended_career', models.CharField(default='Not Assessed', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
