# Generated by Django 6.1 on 2026-09-04 08:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_recommendation', '0003_mockinterview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userskillassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userskillassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userskillassessment',
            name='career_interest',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userskillassessment',
            name='enjoyed_field',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userskillassessment',
            name='recommended_career',
            field=models.CharField(default='Not Assessed', max_length=150),
        ),
        migrations.AlterField(
            model_name='userskillassessment',
            name='selected_skills',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('education', models.CharField(blank=True, max_length=150)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('career_goal', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
