# Generated by Django 5.2.17 on 2026-09-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_recommendation', '0004_userskillassessment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskillassessment',
            name='skill_levels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
