# Generated by Django 5.2.17 on 2026-09-09 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_recommendation', '0005_userskillassessment_skill_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_profile_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
