# Generated by Django 5.2.17 on 2026-09-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_recommendation', '0006_studentprofile_is_profile_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskillassessment',
            name='learning_progress',
            field=models.IntegerField(default=0),
        ),
    ]
