# Generated by Django 5.2.17 on 2026-09-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_recommendation', '0007_userskillassessment_learning_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskillassessment',
            name='learning_progress',
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='better_answer_tip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='communication_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='improvements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='relevance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='technical_score',
            field=models.IntegerField(default=0),
        ),
    ]
