# Generated by Django 5.2.17 on 2026-09-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_recommendation', '0008_remove_userskillassessment_learning_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
