# Generated by Django 5.2.17 on 2026-09-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_recommendation', '0009_resume_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskillassessment',
            name='completed_learning_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userskillassessment',
            name='learning_progress',
            field=models.IntegerField(default=0),
        ),
    ]
